version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /compiler/cli
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /compiler/compiler_fuzzer
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /compiler/frontend
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /compiler/fuzzer
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /compiler/language_server
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: /compiler/vm
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /vscode_extension
    schedule:
      interval: daily
