version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - 'T: Build'

  - package-ecosystem: cargo
    directory: /compiler/cli
    schedule:
      interval: daily
    labels:
      - 'T: Build'
  - package-ecosystem: cargo
    directory: /compiler/formatter
    schedule:
      interval: daily
    labels:
      - 'T: Build'
  - package-ecosystem: cargo
    directory: /compiler/frontend
    schedule:
      interval: daily
    labels:
      - 'T: Build'
  - package-ecosystem: cargo
    directory: /compiler/fuzzer
    schedule:
      interval: daily
    labels:
      - 'T: Build'
  - package-ecosystem: cargo
    directory: /compiler/language_server
    schedule:
      interval: daily
    labels:
      - 'T: Build'
  - package-ecosystem: cargo
    directory: /compiler/vm
    schedule:
      interval: daily
    labels:
      - 'T: Build'
  - package-ecosystem: cargo
    directory: /compiler/vm/fuzz
    schedule:
      interval: daily
    labels:
      - 'T: Build'

  - package-ecosystem: npm
    directory: /vscode_extension
    schedule:
      interval: daily
    groups:
      glob:
        patterns:
          - glob
          - '@types/glob'
      mocha:
        patterns:
          - mocha
          - '@types/mocha'
      prettier:
        patterns:
          - prettier
          - '*-prettier'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
    labels:
      - 'T: Build'
