version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'T: Build'

  - package-ecosystem: cargo
    directories:
      - compiler_v4
      - compiler/backend_inkwell
      - compiler/cli
      - compiler/formatter
      - compiler/formatter/fuzz
      - compiler/frontend
      - compiler/fuzzer
      - compiler/language_server
      - compiler/vm
      - compiler/vm/fuzz
    schedule:
      interval: weekly
    labels:
      - 'T: Build'

  - package-ecosystem: npm
    directories:
      - /vscode_extension
      - /vscode_extension_v4
    schedule:
      interval: weekly
    labels:
      - 'T: Build'
    groups:
      glob:
        patterns:
          - glob
          - '@types/glob'
      mocha:
        patterns:
          - mocha
          - '@types/mocha'
      prettier:
        patterns:
          - prettier
          - '*-prettier'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
