version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'cargo'
    directory: '/new-new-packages/compiler'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/new-new-packages/vscode_extension'
    schedule:
      interval: 'weekly'
