'P: Builtins':
  - packages/Builtins/**/*
'P: Compiler: CLI':
  - compiler/cli/**/*
'P: Compiler: Formatter':
  - compiler/formatter/**/*
'P: Compiler: Frontend':
  - compiler/frontend/**/*
'P: Compiler: Fuzzer':
  - compiler/fuzzer/**/*
'P: Compiler: Inkwell Backend':
  - compiler/backend_inkwell/**/*
'P: Compiler: Language Server':
  - compiler/language_server/**/*
'P: Compiler: VM':
  - compiler/vm/**/*
'P: Compiler: VS Code Extension':
  - vscode_extension/**/*
'P: Core':
  - packages/Core/**/*
