[workspace]
resolver = "2"
members = [
    "compiler/backend_inkwell",
    "compiler/cli",
    "compiler/frontend",
    "compiler/fuzzer",
    "compiler/formatter",
    "compiler/formatter/fuzz",
    "compiler/language_server",
    "compiler/vm",
    "compiler/vm/fuzz",
]

[workspace.package]
edition = "2021"
rust-version = "1.78.0"
