[workspace]

members = [
    "compiler/cli",
    "compiler/frontend",
    "compiler/fuzzer",
    "compiler/language_server",
    "compiler/trace_server",
    "compiler/tracer",
    "compiler/vm",
    "compiler/vm/fuzz",
]

[profile.release]
# https://github.com/flamegraph-rs/flamegraph#usage-with-benchmarks
debug = true
