[package]
name = "candy_formatter"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[lib]

[dependencies]
candy_frontend = { path = "../frontend" }
derive_more = "0.99.17"
extension-trait = "1.0.1"
itertools = "0.12.0"
traversal = "0.1.2"
unicode-width = "0.1.10"
