[package]
name = "candy_formatter"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[lib]

[dependencies]
candy_frontend = { path = "../frontend" }
derive_more = "0.99.17"
extension-trait = "1.0.1"
itertools = "0.10.0"
unicode-width = "0.1.10"
