name: PR

on: pull_request

jobs:
  add-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          configuration-path: .github/labels.yaml
          repo-token: '${{ secrets.BOT_TOKEN }}'

  assign-author:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - uses: samspills/assign-pr-to-author@v1.0
        with:
          repo-token: '${{ secrets.BOT_TOKEN }}'
